apiVersion: apps/v1
kind: Deployment

metadata:
  name:      fastapi

  labels:
    app.kubernetes.io/name:       fastapi
    app.kubernetes.io/component:  backend
    app.kubernetes.io/managed-by: kubectl
    environment:                  production

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastapi

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:       1     # allow 1 extra pod during rollout
      maxUnavailable: 0     # keep old pod running until new one is ready

  template:
    metadata:
      labels:
        app:                          fastapi
        app.kubernetes.io/name:       fastapi
        app.kubernetes.io/component:  backend
        environment:                  production

    spec:
      initContainers:
        - name:   sync-data
          image:  busybox:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /data/raw/uploads /data/feedback /data/processed /models
              chown -R 1000:1000 /data /models
          volumeMounts:
            - name: rag-data
              mountPath: /data

        - name:   wait-for-index
          image:  busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for FAISS index at /data/models/faiss_index..."
              while [ ! -d /data/models/faiss_index ]; do
                echo "Index not found yet, sleeping 5s..."
                sleep 5
              done
              echo "FAISS index found. Proceeding."
          volumeMounts:
            - name: rag-data
              mountPath: /data

      containers:
        - name:  fastapi
          image: wodlldd/production-rag-system:latest
          imagePullPolicy: Always

          ports:
            - name:          http
              containerPort: 8000
              protocol:      TCP

          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key:  GOOGLE_API_KEY

          volumeMounts:
            - name:      rag-data
              mountPath: /app/data

          resources:
            requests:
              cpu:    "500m"
              memory: "4Gi"
            limits:
              cpu:    "2000m"
              memory: "6Gi"

          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds:       15
            failureThreshold:    4

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds:       10
            failureThreshold:    10

      volumes:
        - name: rag-data
          persistentVolumeClaim:
            claimName: rag-data-pvc

      restartPolicy: Always
