apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ingest2
spec:
  restartPolicy: Never
  containers:
    - name: ingest
      image: wodlldd/production-rag-system:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: rag-data
          mountPath: /app/data
        - name: upload-files
          mountPath: /upload-files
      env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: GOOGLE_API_KEY
  volumes:
    - name: rag-data
      persistentVolumeClaim:
        claimName: rag-data-pvc
    - name: upload-files
      configMap:
        name: upload-files
